# Generated by Django 4.2.5 on 2023-11-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=30, null=True)),
                ('date_field', models.DateField(auto_now=True)),
                ('file_desc', models.CharField(default=None, max_length=255, null=True)),
                ('file_name', models.CharField(max_length=55, null=True)),
                ('status', models.CharField(max_length=12, null=True)),
                ('myfiles', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='file_upload',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('my_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='myclassnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=30, null=True)),
                ('date_field', models.DateField(auto_now=True)),
                ('file_desc', models.CharField(default=None, max_length=255, null=True)),
                ('file_name', models.CharField(max_length=55, null=True)),
                ('status', models.CharField(max_length=12, null=True)),
                ('myfiles', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='myuploadjournels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=30, null=True)),
                ('date_field', models.DateField(auto_now=True)),
                ('file_desc', models.CharField(default=None, max_length=255, null=True)),
                ('file_name', models.CharField(max_length=55, null=True)),
                ('status', models.CharField(max_length=12, null=True)),
                ('myfiles', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='myuploadstaff',
            fields=[
                ('roll_no', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=20, null=True)),
                ('f_desc', models.CharField(default=None, max_length=255, null=True)),
                ('f_name', models.CharField(default=None, max_length=25, null=True)),
                ('myfiles', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='myuploadSTUDENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=30, null=True)),
                ('date_field', models.DateField(auto_now=True)),
                ('file_desc', models.CharField(default=None, max_length=255, null=True)),
                ('file_name', models.CharField(max_length=55, null=True)),
                ('status', models.CharField(max_length=12, null=True)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
